In [59]:
import numpy as np

In [60]:
# examples of velocity caclualtions
def vel(m, h, P , P_electric = 250):
    ### aer. resistence
    Cd = 1.18
    A = 0.83 #m^2
    rho = 1.18 #kg/m^3

    c_Fd = rho*Cd*A*0.5

    ### rolling resistance
    Cr = 0.01
    g = 9.81 #m/s^2
    
    eta = 0.95
        
    c0 = P*eta
    c1 = (m*g* ( Cr*np.cos( np.arctan(h) ) + np.sin( np.arctan(h) ) ))
    c3 = c_Fd
    
    v_max = 30 #km/h

    coefs = [c3, 0, c1, -eta*P]
    coefs_electric = [c3, 0, c1, -eta*(P+P_electric)]        
    v = np.max(np.real(3.6*np.roots(coefs)))
    v_electric = np.max(np.real(3.6*np.roots(coefs_electric)))
    if v > 25:
        #print('up-cyclist only')
        return min(v, v_max)
    else:
        #print('up-electric')
        return min(v_electric, 25)

In [61]:
v1 = vel(150, 30/700, 125)
v1

14.68650680718316

In [62]:
def test_vel(p_i, p_j, p_int, m, P_human):
    
    Dx_ij = abs(p_j[0] - p_i[0])
    Dx_i_int = abs(p_int[0] - p_i[0])
    Dx_int_j = abs(p_j[0] - p_int[0])
    print(Dx_ij, Dx_i_int, Dx_int_j)
    
    Dy_ij = p_j[1] - p_i[1]
    Dy_i_int = p_int[1] - p_i[1]
    Dy_int_j = p_j[1] - p_int[1]
    
    grad_i_j = Dy_ij/Dx_ij
    grad_i_int = Dy_i_int/Dx_i_int
    grad_int_j = Dy_int_j/Dx_int_j

    v_i_j = vel(m, grad_i_j, P_h)
    v_i_int = vel(m, grad_i_int, P_h)
    v_int_j = vel(m, grad_int_j, P_h)
    
    v_j_i = vel(m, -grad_i_j, P_h)
    v_j_int = vel(m, -grad_int_j, P_h)
    v_int_i = vel(m, -grad_i_int, P_h)
    
    t_ij = Dx_ij/v_i_j
    t_ij_int = Dx_i_int/v_i_int + Dx_int_j/v_int_j
    
    t_ji = Dx_ij/v_j_i
    t_ji_int = Dx_int_j/v_j_int + Dx_i_int/v_int_i
    
    return [v_i_j, v_i_int, v_int_j], [t_ij, t_ij_int], [v_j_i, v_j_int, v_int_i], [t_ji, t_ji_int]

In [93]:
p_i = (0, 0)
p_j = (750, 30)
p_int = (600, 5)

m = 100 # kg
P_h = 150 # W


v1, t1, v2, t2 = test_vel(p_i, p_j, p_int, m, P_h)

750 600 150


In [94]:
np.round(v1, 2)

array([20.3 , 25.  ,  7.87])

In [95]:
np.round(t1, 2)

array([36.94, 43.05])

In [96]:
np.round(v2, 2)

array([30, 30, 25])

In [97]:
np.round(t2, 2)

array([25., 29.])

In [68]:
p_i = (0, 0)
p_j = (750, 10)
p_int = (300, 30)

m = 100 # kg
P_h = 150 # W

v1, t1, v2, t2 = test_vel(p_i, p_j, p_int, m, P_h)

750 300 450


In [69]:
v1

[25, 12.019423406425854, 30]

In [70]:
t1

[30.0, 39.95959996214238]

In [71]:
v2

[25, 19.470482409310197, 30]

In [72]:
t2

[30.0, 33.11190809452279]

In [83]:
p_i = (0, 0)
p_j = (800, 0)
p_int = (400, 30)

m = 100 # kg
P_h = 150 # W

v1, t1, v2, t2 = test_vel(p_i, p_j, p_int, m, P_h)

800 400 400


In [84]:
v1

[25, 14.736050400156037, 30]

In [85]:
t1

[32.0, 40.477648746082224]

In [86]:
v2

[25, 14.736050400156037, 30]

In [87]:
t2

[32.0, 40.477648746082224]